config/routes.rb
 Rails.application.routes.draw do
  get 'payments/new'

  scope '(:locale)', locale: /fr|es/ do
    resources :cocktails
  end

  require "sidekiq/web"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => "cocktails#index"

  #authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  #end
  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]
  end
  resources :cocktails, only: [:index, :show]

  resources :users do
    resources :events do
      resources :reviews, only: [:new, :create]
    end

    resources :reviews, only: [:index]

    resources :professionals, only: [:show, :new, :create, :edit, :update] do
      resources :events, only: [:index, :show], controller: 'professionals/events' do
        put 'confirm', to: 'professionals/events#confirm'
        resources :reviews, only: [:index]
      end
    end
  end

  resources :doses, only: [:destroy]
  resources :events, only: [:destroy]

end

app/models/professional.rb
class Professional < ActiveRecord::Base
  # after_create :send_welcome_email

  extend Enumerize
  geocoded_by :business_address
  after_validation :geocode, if: :business_address_changed?

  belongs_to :user

  has_many :events
  has_many :users, through: :events
  has_many :reviews, as: :reviewable

  enumerize :professional_role, in: [:barman, :brasseur, :sommelier, :cellar_man]

  validates_presence_of :name, :business_address, :description, :phone_number, :professional_role

  def rate
    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    self.rating = sum / reviews.size
    self.save
  end

private

  def send_welcome_email
    UserMailer.welcome_pro(self).deliver_now
  end
end

app/controllers/professionals/events_controller.rb
module Professionals
  class EventsController < ApplicationController
    def index
      @events = current_user.professional.events
      @review = Review.new

    end

    def confirm
      @event = Event.find(params[:event_id])
      @event.is_confirmed = true

      if @event.save
        respond_to do |format|
          # format.html { redirect_to user_professional_events(current_user) }
          format.js  # <-- will render `app/views/reviews/create.js.erb`
        end
      else
        respond_to do |format|
          # format.html { render 'professionals/events/index' }
          format.js  # <-- idem
        end
      end
    end
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController

  def index
    @professionals = Professional.all
  end

  def show
    user = User.find(params[:user_id])
    @professional = user.professional
    @professional_coordinates = { lat: @professional.latitude, lng: @professional.longitude}
    @review = Review.new
  end

  def new
    @professional = current_user.professionals.build
  end

  def create
    @professional = current_user.professionals.build(professional_params)
    @professional.user = current_user
    @professional.name = current_user.name

    if @professional.save
      redirect_to user_professional_path(current_user, @professional)
    else
      render :new
    end
  end

  def edit
    @professional = current_user.professional
  end

  def update
    @professional = current_user.professional
    if @professional.update(professional_params)
      redirect_to user_professional_path(current_user, @professional)
    else
      render :edit
    end
  end

private

  def professional_params
    params.require(:professional).permit(:max_travel_range, :professional_role, :phone_number, :business_address, :description)
  end
end

app/views/professionals/_index.html.erb
<div id="map" style="width: 100%; height: 650px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/professionals/_map_box.html.erb
<h6><%= professional.user.name %></h6>
<p><em><%= professional.description %></em></p>
<p>
  <% if professional.rating %>
    <% if professional.rating == 0 %>
      <i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating < 1 && professional.rating > 0 %>
      <i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating == 1 %>
      <i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating < 2 && professional.rating > 1 %>
      <i class="fa fa-star"><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></i>
    <% end %>
    <% if professional.rating == 2 %>
      <i class="fa fa-star"></i><i class="fa fa-star"><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></i>
    <% end %>
    <% if professional.rating < 3 && professional.rating > 2 %>
      <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating == 3 %>
      <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating < 4 && professional.rating > 3 %>
      <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating == 4 %>
      <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i>
    <% end %>
    <% if professional.rating < 5 && professional.rating > 4 %>
      <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i>
    <% end %>
    <% if professional.rating == 5 %>
      <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
    <% end %>
<% end %>
</p>
<p><a data-id="<%= professional.id %>" data-name="<%= professional.user.name %>" class="btn btn-xs btn-color-line professional-chosen" onclick="fillForm(this);">Choose me</a></p>

app/views/professionals/edit.html.erb
<section class="inner-intro inner-intro-small bg-imglogin overlay-dark light-color parallax parallax-background2">
    <div class="container">
        <div class="row title">
            <h2 class="h2">Edit your</h2>
            <h3>professional profile</h3>
        </div>
    </div>
</section>
<div class="clearfix"></div>


<section id="Pricing" class="ptb ptb-sm-80">
    <div class="container">
        <div class="col-xs-12 col-sm-6  col-sm-offset-3">
          <div class="login">
            <h2>Edit your profile</h2>

            <%= simple_form_for([current_user, @professional]) do |f| %>
              <%= f.error_notification %>

              <div class="form-field-wrapper">
                <%= f.input :professional_role, collection: Professional.professional_role.options %>
                <%= f.input :description %>
                <%= f.input :max_travel_range %>
                <%= f.input :phone_number %>
                <%= f.input :business_address, input_html: { id: "user_input_autocomplete_address"} %>
              </div>

              <div class="form-actions">
                <%= f.button :submit, "Edit", class:"btn btn-md btn-color-line" %>
                <%= link_to "CANCEL", user_professional_path(current_user, @professional), style:"margin-left: 10px;" %>
              </div>
            <% end %>

          </div>
        </div>
    </div>
</section>

app/views/professionals/new.html.erb
<section class="inner-intro bg-imgparty overlay-dark light-color parallax parallax-background2">
    <div class="container">
        <div class="row title">
            <h2 class="h2">Register as professional</h2>
        </div>
    </div>
</section>
<div class="clearfix"></div>



<!-- End Intro Section -->
<section id="Pricing" class="ptb ptb-sm-80">
  <div class="container">
    <div class="col-xs-12 col-sm-6  col-sm-offset-3">

        <h2>Register</h2>

        <%= simple_form_for([current_user, @professional]) do |f| %>
          <%= f.error_notification %>

          <div class="form-field-wrapper">
            <%= f.input :professional_role, collection: Professional.professional_role.options %>
            <%= f.input :description, placeholder:'Good listener, 5 years of experience...etc' %>
            <%= f.input :max_travel_range, placeholder:'Maximum distance to an event (in km)' %>
            <%= f.input :phone_number, placeholder:'0123456789' %>
            <%= f.input :business_address, input_html: { id: "user_input_autocomplete_address"}, placeholder: "Your business address" %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Register", class:"btn btn-md btn-color-line"%>
            <%= link_to "cancel", user_path(current_user), style:"margin-left: 10px;" %>
          </div>
        <% end %>

    </div>
  </div>
</section>

app/views/professionals/show.html.erb
<section class="inner-intro bg-imgprofile overlay-dark light-color parallax parallax-background2">
    <div class="container">
        <div class="row title">
            <h2 class="h2"><%= current_user.name %></h2>
            <h3>Professional account</h3>
        </div>
    </div>
</section>
<div class="clearfix"></div>
        <!-- End Intro Section -->
          <!-- About Section -->
<section class="ptb ptb-sm-80">

</section>

  <!-- Team -->






<section class="pb pb-sm-80">
  <div class="container">
          <!--Team Carousel -->
    <div class="row">

      <div class="col-md-4">
        <div class="item">
          <div class="team-item nf-col-padding">
            <div class="team-item-img">
              <%= image_tag current_user.picture, alt:"professional picture" %>
              <div class="team-item-detail">
                <div class="team-item-detail-inner light-color">
                  <h5><%= current_user.name %></h5>
                  <ul class="list-unstyled">
                    <li class="profile-title"><i class="fa fa-envelope-o"></i>  <%= current_user.email%></li>
                    <li class="profile-title"><i class="fa fa-chevron-circle-right"></i> <%= @professional.description%></li>
                    <%  if @professional.phone_number %>
                    <li class="profile-title"><i class="fa fa-phone"></i>  <%= @professional.phone_number%></li>
                    <% end %>
                    <% if @professional.business_address %>
                    <li class="profile-title"><i class="fa fa-map-marker"></i>  <%= @professional.business_address%></li>
                    <% end %>
                    <% if @professional.rating %>
                        <% if @professional.rating == 0 %>
                          <li><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating < 1 && @professional.rating > 0 %>
                          <li><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating == 1 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating < 2 && @professional.rating > 1 %>
                          <li><i class="fa fa-star"><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></i></li>
                        <% end %>
                        <% if @professional.rating == 2 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></i></li>
                        <% end %>
                        <% if @professional.rating < 3 && @professional.rating > 2 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating == 3 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating < 4 && @professional.rating > 3 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating == 4 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @professional.rating < 5 && @professional.rating > 4 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i></li>
                        <% end %>
                        <% if @professional.rating == 5 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></li>
                        <% end %>
                    <% end %>
                  </ul>
                  <ul class="social">
                    <li><a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://www.twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="container text-center">
          <div class="row text-center">
            <div class="col-md-4 col-md-offset-2">
              <div class="page-icon-top"><i class="fa fa-calendar-check-o"></i></div>
              <%= link_to "Your events", user_professional_events_path(current_user, current_user.professional), class:"btn btn-xd btn-color-line"%>
            </div>
          </div>
          <br>
          <br>
          <div class="row text-center">
            <div class="col-md-4">
              <div class="page-icon-top"><i class="fa fa-user"></i></div>
              <%= link_to "Edit your profile", edit_user_professional_path(current_user, current_user.professional), class:"btn btn-xd btn-color-line"%>
            </div>
            <div class="col-md-4">
              <div class="page-icon-top"><i class="fa fa-child"></i></div>
                <%= link_to "Back to user profile", user_path(current_user), class:"btn btn-xd btn-color-line"%>
            </div>
          </div>
        </div>
      </div>


                <!--End Team Carousel -->
    </div>
  </div>
</section>
<!-- End Team -->




<!-- Testimonials -->
<section id="testimonial" class="overlay-dark80 dark-bg ptb ptb-sm-80" style="background-image: url('http://7x24fl-al.org/Resources/Pictures/cocktail_drinks_1920x1080_89001.jpg');  background-position: 0% 900.5px;" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="owl-carousel testimonial-carousel nf-carousel-theme white">
            <div class="item">
                <div class="testimonial text-center dark-color">
                    <div class="container-icon"><i class="fa fa-quote-right"></i></div>
                    <% if current_user.professional.reviews.empty? %>
                    <p> No reviews...</p>
                    <% else %>
                    <p>"<%= current_user.professional.reviews.last.content %>"</p>
                    <h6 class="quote-author"><%=  current_user.professional.reviews.last.reviewer.name %></h6>
                    <% end %>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End Testimonials -->