config/routes.rb
 Rails.application.routes.draw do
  get 'payments/new'

  scope '(:locale)', locale: /fr|es/ do
    resources :cocktails
  end

  require "sidekiq/web"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => "cocktails#index"

  #authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  #end
  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]
  end
  resources :cocktails, only: [:index, :show]

  resources :users do
    resources :events do
      resources :reviews, only: [:new, :create]
    end

    resources :reviews, only: [:index]

    resources :professionals, only: [:show, :new, :create, :edit, :update] do
      resources :events, only: [:index, :show], controller: 'professionals/events' do
        put 'confirm', to: 'professionals/events#confirm'
        resources :reviews, only: [:index]
      end
    end
  end

  resources :doses, only: [:destroy]
  resources :events, only: [:destroy]

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  # mount_uploader :image, ImageUploader
  include PgSearch
  pg_search_scope :kinda_spelled_like,
                  :against => :name,
                  :using => :trigram

  has_many :ingredients, through: :doses
  has_many :doses, dependent: :destroy
  has_many :reviews, as: :reviewable

  validates_presence_of :name, :image, :recipe_steps
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    nb_of_doses = @cocktail.doses.count
    @offset = get_offset(nb_of_doses)
  end

  def get_offset(nb_of_doses)
    offset = 0
    case nb_of_doses
    when 2
      offset = 4
    when 3
      offset = 3
    when 4
      offset = 2
    when 5
      offset = 1
    end
    offset
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      doses = Dose.all
      doses.each do |dose|
        case dose.ingredient_id
        when 7
          Cocktail.find(dose.cocktail_id).alcohol_type = "vodka"
        when 19
          Cocktail.find(dose.cocktail_id).alcohol_type = "rhum"
        when 20
          Cocktail.find(dose.cocktail_id).alcohol_type = "gin"
        when 8 || 31
          Cocktail.find(dose.cocktail_id).alcohol_type = "whisky"
        when 17
          Cocktail.find(dose.cocktail_id).alcohol_type = "tequila"
        end
      end
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy

    redirect_to cocktails_path
  end

private

  def cocktail_params
    params.require(:cocktail).permit(:name, :image, :image_cache)
  end
end

app/views/cocktails/index.html.erb
<%= render 'shared/header' %>

<div id="video" style="height: 100vh; width: 100%; position: relative;" class="hidden-xs ">
  <div class="full-cap-wraper">
    <div class="content-caption overlay-dark light-color">
      <div class="container">
        <h1>Find a barman</h1>
        <h2 class="h2">For your event</h2>
        <br>
        <div>
          <% if user_signed_in? %>
            <%= link_to "Create an Event", new_user_event_path(current_user), class: "btn btn-md btn-white-line xs-hidden" %>
          <% else %>
            <%= link_to "Create an Event", new_user_path, class: "btn btn-md btn-white-line" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Intro Video Section -->
<div id="bg" style="height: 100vh; width: 100%; position: relative;" class="hidden-sm hidden-md hidden-lg ">
  <div class="full-cap-wraper">
    <div class="content-caption overlay-dark light-color">
      <div class="container">
        <h1>Find a barman</h1>
        <h2 class="h2">For your event</h2>
        <br>
        <div>
          <% if user_signed_in? %>
            <%= link_to "Create an Event", new_user_event_path(current_user), class: "btn btn-md btn-white-line " %>
          <% else %>
            <%= link_to "Create an Event", new_user_path, class: "btn btn-md btn-white-line xs-hidden" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Intro Video Section -->

<div class="clearfix"></div>


<section id="service" class="ptb ptb-sm-80">
  <div class="wow fadeInLeft container text-center">
      <h3>Our Services</h3>
      <div class="spacer-60"></div>
      <div class="row">
          <div class="col-md-4 col-sm-6 mb-45">
              <div class="page-icon-top"><i class="fa fa-calendar-check-o"></i></div>
              <h5>Cocktails</h5>
              <p>Browse our repertoire of cocktails and recipes for inspiration.</p>
          </div>
          <div class="col-md-4 col-sm-6 mb-45">
              <div class="page-icon-top"><i class="fa fa-user"></i></div>
              <h5>Events</h5>
              <p>Create an event and pick a barman from our list of professionals.</p>
          </div>
          <div class="col-md-4 col-sm-6 mb-45">
              <div class="page-icon-top"><i class="fa fa-glass"></i></div>
              <h5>Enjoy</h5>
              <p>Have the piece of mind to know your guests will enjoy top quality service.</p>
          </div>
      </div>
  </div>
</section>



<!-- Counter Section -->
<section id="counter" class="overlay-dark80 light-color ptb-80" style="background-image: url('http://img0.gtsstatic.com/wallpapers/50400dc4c6007b6050e8a36f71bd5516_large.jpeg');  background-position: 0% 950px;" data-stellar-background-ratio="0.5">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-3 mb-sm-30">
                <h1 class="counter" data-count="2310">0</h1>
                <h6>Cocktails</h6>
            </div>
            <div class="col-md-3 mb-sm-30">
                <h1 class="counter" data-count="5054">0</h1>
                <h6>Barmans</h6>
            </div>
            <div class="col-md-3 mb-sm-30">
                <h1 class="counter" data-count="6">0</h1>
                <h6>Countries</h6>
            </div>
            <div class="col-md-3 mb-sm-30">
                <h1 class="counter" data-count="3390">0</h1>
                <h6>Events</h6>
            </div>
        </div>
    </div>
</section>
        <!-- End Counter Section -->



<!-- Work Section -->
<section id="work" class="wow fadeInUp pt pt-sm-80 text-center">
    <div class="container">
        <h3>Our cockails</h3>
        <div class="spacer-30"></div>

        <div class="spacer-30"></div>
    </div>

    <!-- work Filter -->
    <div class="row">
        <ul class="container-filter categories-filter">
            <li><a class="categories active" data-filter="*">All</a></li>
            <li><a class="categories" data-filter=".vodka">Vodka</a></li>
            <li><a class="categories" data-filter=".tequila">Tequila</a></li>
            <li><a class="categories" data-filter=".rhum">Rhum</a></li>
            <li><a class="categories" data-filter=".gin">Gin</a></li>
            <li><a class="categories" data-filter=".whisky">Whisky</a></li>

        </ul>
    </div>
                <!-- End work Filter -->

    <!-- Work Gallary -->
    <div class="container-fluid ">
        <div class="row">
            <div class="container-grid nf-col-4">
              <% @cocktails.each do |cocktail| %>
              <div class="nf-item <%= cocktail.alcohol_type %>">
                    <div class="item-box">
                        <a href= <%= cocktail_path(cocktail.id) %> title= <% cocktail.name %>>
                            <%= image_tag cocktail.image , class:"item-container", alt:"2" %>
                            <div class="item-mask">
                                <div class="item-caption">
                                    <h5 class="white"><%= cocktail.name %></h5>
                                    <p class="white">Show details</p>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>
              <% end %>
            </div>
        </div>
    </div>
    <!-- End Work Gallary -->
</section>
<!-- End Work Section -->
<section >
    <div class="container text-center">
        <div class="spacer-30"></div>
        <div class="spacer-30"></div>
<!--         <div class="spacer-30"></div>
        <div class="row">
          <div class="col-xs-12 col-md-3">

          </div>
          <div class="col-xs-12 col-md-6" id="sear">
            <input type="text" class="input-sm form-full search-term", remote: true, placeholder="&#xf002; Find your cocktail"/>
          </div>
          <div class="col-xs-12 col-md-3">
          </div>
        </div> -->
        <h2>ENJOY!</h2>
        <div class="spacer-30"></div>
        <div class="spacer-30"></div>
    </div>
</section>


  <!-- Testimonials -->
<section id="testimonial" class="overlay-dark80 dark-bg ptb ptb-sm-80" style="background-image: url('http://7x24fl-al.org/Resources/Pictures/cocktail_drinks_1920x1080_89001.jpg');  background-position: 0% 900.5px;" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="owl-carousel testimonial-carousel nf-carousel-theme white">
            <div class="item">
                <div class="testimonial text-center dark-color">
                    <div class="container-icon"><i class="fa fa-quote-right"></i></div>
                    <p class="lead">"Mind Spirit is a platform that helps people find professional barmen for their events"</p>
                    <h6 class="quote-author">Jeff Dunham <span style="font-weight: 400;">( Appel Studio )</span></h6>
                </div>
            </div>
            <div class="item">
                <div class="testimonial text-center dark-color">
                    <div class="container-icon"><i class="fa fa-quote-right"></i></div>
                    <p class="lead">" It's true, you can never eat a pet you name. And anyway, I did my first show in the third grade it would be like a ventriloquist eating his dummy. "</p>
                    <h6 class="quote-author">Alexander Theroux <span style="font-weight: 400;">( USA )</span></h6>
                </div>
            </div>
            <div class="item">
                <div class="testimonial text-center dark-color">
                    <div class="container-icon"><i class="fa fa-quote-right"></i></div>
                    <p class="lead">" We're not leaving here without Buster, man. Leave no crash-test dummy behind! "</p>
                    <h6 class="quote-author">Adam Savage <span style="font-weight: 400;">( Artist )</span></h6>
                </div>
            </div>
        </div>
    </div>
</section>
        <!-- End Testimonials -->

app/views/cocktails/new.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.8) 0%, rgba(0,36,61,0.9) 50%), url('http://res.cloudinary.com/dbgwg7vxg/image/upload/v1457085683/cocktails_xjsqwc.jpg');">
  <div class="banner-content">
    <h2><%= t "new.AddCocktail"%></h2>
    <div class="container cocktail-form">
      <%= simple_form_for(@cocktail) do |f| %>
        <%= f.error_notification %>

        <%= f.input :name, label: false, placeholder: "#{t 'new.Name'}" %>
        <%= f.input :recipe_steps, label: false, :placeholder => "#{t 'new.Description'}"%>
        <%= f.input :image, as: :image_preview, label: false %>
        <%= f.input :image_change, as: :hidden %>

        <%= f.button :submit, :class => 'submit-wagon-button btn' %>
        <%end%>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<!-- Intro Section -->
<section class="full-screen-intro">

    <!-- Bg Image -->
    <div class="media-wapper bg-img cont-h-100per" style="background-image: url(<%= image_path(@cocktail.image) %>);">
    </div>
    <!-- End Bg Image -->

    <!-- Content -->
    <div class="full-cap-wraper overlay-dark80 light-color">
        <div class="content-caption light-color parallax parallax-opacity">
            <div class="container">
                <h1 class=""><%= @cocktail.name %></h1>
                <div class="row">
                    <h5 class="col-md-6 col-md-offset-3">Presented by Mind Spirit</h5>
                </div>
                <br>
                <div>
                  <% if user_signed_in? %>
                    <%= link_to "Find a Barman", new_user_event_path(current_user), class: "btn btn-md btn-white" %>
                  <% else %>
                    <%= link_to "Login to book a barman", new_user_session_path, class: "btn btn-md btn-white" %>
                  <% end %>
                </div>
            </div>
        </div>
    </div>
    <!-- End Content -->

    <!-- Intro Scroll Down -->
    <div class="intro-scroll-down">
        <a class="scroll-down" href="#about">
            <span class="mouse">
                <span class="mouse-dot"></span>
            </span>
        </a>
    </div>
    <!-- End Intro Scroll Down -->
</section>
<div class="clearfix"></div>
<!-- End Intro Section -->

<hr/>

<!-- Process -->
<section id="process" class="ptb ptb-sm-80">
    <div class="wow fadeInLeft container text-center">
      <h3>Ingredients</h3>
      <div class="spacer-60"></div>
      <div class="row">
        <% @cocktail.doses.each do |dose| %>
          <% if @cocktail.doses.first == dose %>
            <div class="col-md-2 col-md-offset-<%= @offset %> col-sm-4 col-xs-6">
                <div class="page-icon-top"><i class="ion ion-ios-people-outline"></i></div>
                <h6><%= dose.ingredient.name %>: <%= dose.quantity %></h6>
            </div>
          <% else %>
            <div class="col-md-2 col-sm-4 col-xs-6">
              <div class="page-icon-top"><i class="ion ion-ios-people-outline"></i></div>
              <h6><%= dose.ingredient.name %>: <%= dose.quantity %></h6>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
</section>
<!-- End Process -->

<hr />

<section id="about" class="wow fadeIn ptb ptb-sm-80">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="h4">Recipe</h3>
                <div class="spacer-15"></div>
                <p class="lead"><%= @cocktail.recipe_steps %></p>
            </div>
        </div>
    </div>
</section>

<a class="scroll-top">
    <i class="fa fa-angle-double-up"></i>
</a>