config/routes.rb
 Rails.application.routes.draw do
  get 'payments/new'

  scope '(:locale)', locale: /fr|es/ do
    resources :cocktails
  end

  require "sidekiq/web"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => "cocktails#index"

  #authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  #end
  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]
  end
  resources :cocktails, only: [:index, :show]

  resources :users do
    resources :events do
      resources :reviews, only: [:new, :create]
    end

    resources :reviews, only: [:index]

    resources :professionals, only: [:show, :new, :create, :edit, :update] do
      resources :events, only: [:index, :show], controller: 'professionals/events' do
        put 'confirm', to: 'professionals/events#confirm'
        resources :reviews, only: [:index]
      end
    end
  end

  resources :doses, only: [:destroy]
  resources :events, only: [:destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  # after_create :send_welcome_email
  # after_commit :find_user_full_name

  has_many :professionals, through: :events
  has_many :events, through: :orders
  has_many :orders
  has_one :professional
  has_many :reviews, as: :reviewable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

  validates_presence_of :name

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.name = "#{user.first_name} #{user.last_name}"
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def rate
    sum = 0
    reviews.each do |review|
      sum += review.rating
    end
    self.rating = sum / reviews.size
    self.save
  end

  private

  def send_welcome_email
    UserMailer.welcome_user(self).deliver_now
  end

  def find_user_full_name
    FindUserFullNameJob.perform_later(self.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @review = Review.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :phone_number, :address)
  end
end

app/views/users/edit.html.erb
<section class="inner-intro inner-intro-small bg-imglogin overlay-dark light-color parallax parallax-background2">
    <div class="container">
        <div class="row title">
            <h2 class="h2">Edit your profile</h2>
        </div>
    </div>
</section>
<div class="clearfix"></div>
<!-- End Intro Section -->
<section id="Pricing" class="ptb ptb-sm-80">
    <div class="container">
        <div class="col-xs-12 col-sm-6  col-sm-offset-3">
            <div class="login">
                <h2><%= t '.EditProfile'%> </h2>
                <%= simple_form_for(@user) do |f| %>
                    <%= f.error_notification %>

                    <div class="form-field-wrapper">
                        <%= f.input :name, placeholder:"#{t 'users.edit.YourName'}"%>
                        <%= f.input :phone_number, placeholder:"#{t 'users.edit.YourPhone'}"%>
                        <%= f.input :address, input_html: { id: "user_input_autocomplete_address"}, placeholder:"#{t 'users.edit.YourAddress'}" %>
                    </div>

                    <div class="form-actions">
                        <%= f.button :submit,"#{t 'users.edit.Edit'}", class:"btn btn-md btn-color-line" %>
                        <%= link_to "CANCEL", user_path(current_user), style:"margin-left: 10px;"%>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="inner-intro bg-imgprofile overlay-dark light-color parallax parallax-background2">
    <div class="container">
        <div class="row title">
            <h2 class="h2"><%= current_user.name %></h2>

            <h3>User account</h3>
        </div>
    </div>
</section>
<div class="clearfix"></div>
        <!-- End Intro Section -->
          <!-- About Section -->
<section class="ptb ptb-sm-80">

</section>

  <!-- Team -->

<section class="pb pb-sm-80">
  <div class="container">
          <!--Team Carousel -->
    <div class="row">

      <div class="col-md-4">
        <div class="item">
          <div class="team-item nf-col-padding">
            <div class="team-item-img">
              <%= image_tag current_user.picture, alt:"user picture" %>
              <div class="team-item-detail">
                <div class="team-item-detail-inner light-color">
                  <h5><%= current_user.name %></h5>
                  <ul class="list-unstyled">
                      <li class="profile-title"><i class="fa fa-envelope-o"></i>  <%= @user.email%></li>
                    <%  if @user.phone_number %>
                      <li class="profile-title"><i class="fa fa-phone"></i>  <%= @user.phone_number%></li>
                    <% end %>
                    <% if @user.address %>
                      <li class="profile-title"><i class="fa fa-map-marker"></i>  <%= @user.address%></li>
                    <% end %>
                    <% if @user.rating %>
                        <% if @user.rating == 0 %>
                          <li><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating < 1 && @user.rating > 0 %>
                          <li><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating == 1 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating < 2 && @user.rating > 1 %>
                          <li><i class="fa fa-star"><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></i></li>
                        <% end %>
                        <% if @user.rating == 2 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></i></li>
                        <% end %>
                        <% if @user.rating < 3 && @user.rating > 2 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating == 3 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating < 4 && @user.rating > 3 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating == 4 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-o"></i></li>
                        <% end %>
                        <% if @user.rating < 5 && @user.rating > 4 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half-o"></i></li>
                        <% end %>
                        <% if @user.rating == 5 %>
                          <li><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></li>
                        <% end %>
                    <% end %>
                  </ul>
                  <ul class="social">
                    <li><a href="https://www.facebook.com/" target="_blank"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://www.twitter.com/" target="_blank"><i class="fa fa-twitter"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <div class="container text-center">
          <div class="row text-center">
            <div class="col-md-4">
              <div class="page-icon-top"><i class="fa fa-calendar-plus-o"></i></div>

               <%= link_to "Create an event", new_user_event_path(current_user), class:"btn btn-xd btn-color-line"%>
            </div>
            <div class="col-md-4">
              <div class="page-icon-top"><i class="fa fa-calendar-check-o"></i></div>
              <%= link_to "Your events", user_events_path(current_user), class:"btn btn-xd btn-color-line"%>
            </div>
          </div>
          <br>
          <br>
          <div class="row text-center">
            <div class="col-md-4">
              <div class="page-icon-top"><i class="fa fa-user"></i></div>
              <%= link_to "Edit your profile", edit_user_path(current_user), class:"btn btn-xd btn-color-line"%>
            </div>
            <% if @user.professional %>
              <div class="col-md-4">
                <div class="page-icon-top"><i class="fa fa-product-hunt"></i></div>
                  <%= link_to "Pro Account", user_professional_path(@user, @user.professional), class:"btn btn-xd btn-color-line"%>
              </div>
            <% else %>
              <div class="col-md-4">
                <div class="page-icon-top"><i class="fa fa-product-hunt"></i></div>
                  <%= link_to "Register as professional", new_user_professional_path(current_user), class:"btn btn-xd btn-color-line"%>
              </div>
            <% end %>
          </div>
        </div>
      </div>


                <!--End Team Carousel -->
    </div>
  </div>
</section>
<!-- End Team -->




<!-- Testimonials -->
<section id="testimonial" class="overlay-dark80 dark-bg ptb ptb-sm-80" style="background-image: url('http://7x24fl-al.org/Resources/Pictures/cocktail_drinks_1920x1080_89001.jpg');  background-position: 0% 900.5px;" data-stellar-background-ratio="0.5">
    <div class="container">
        <div class="owl-carousel testimonial-carousel nf-carousel-theme white">
            <div class="item">
                <div class="testimonial text-center dark-color">
                    <div class="container-icon"><i class="fa fa-quote-right"></i></div>
                    <% if current_user.reviews.empty? %>
                    <p> No reviews...</p>
                    <% else %>
                    <p>"<%= current_user.reviews.last.content %>"</p>
                    <h6 class="quote-author"> <%=  current_user.reviews.last.reviewer.user.name %> <span style="font-weight: 400;">(<%= current_user.reviews.last.reviewer.professional_role %>)</span></h6>
                    <% end %>
                </div>
            </div>

        </div>
    </div>
</section>
<!-- End Testimonials -->