config/routes.rb
 Rails.application.routes.draw do
  get 'payments/new'

  scope '(:locale)', locale: /fr|es/ do
    resources :cocktails
  end

  require "sidekiq/web"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root :to => "cocktails#index"

  #authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  #end
  resources :orders, only: [:show] do
    resources :payments, only: [:new, :create]
  end
  resources :cocktails, only: [:index, :show]

  resources :users do
    resources :events do
      resources :reviews, only: [:new, :create]
    end

    resources :reviews, only: [:index]

    resources :professionals, only: [:show, :new, :create, :edit, :update] do
      resources :events, only: [:index, :show], controller: 'professionals/events' do
        put 'confirm', to: 'professionals/events#confirm'
        resources :reviews, only: [:index]
      end
    end
  end

  resources :doses, only: [:destroy]
  resources :events, only: [:destroy]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
        <!-- FOOTER -->
        <footer class="footer pt-80">
            <div class="container">
                <div class="row mb-60">
                    <!-- Logo -->
                    <div class="col-md-3 col-sm-3 col-xs-12 mb-xs-30">
                      <%= link_to "Mind Spirit", root_path, class:"footer-logo", style:"font-family:'Alex Brush',cursive;font-size: 20px;" %>
                    </div>
                    <!-- Logo -->

                    <!-- Newsletter -->
                    <div class="col-md-4 col-sm-5 col-xs-12 mb-xs-30">

                    </div>
                    <!-- End Newsletter -->

                    <!-- Social -->
                    <div class="col-md-3 col-md-offset-2 col-sm-4 col-xs-12">
                        <ul class="social">
                            <li><a target="_blank" href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a></li>
                            <li><a target="_blank" href="https://instagram.com/"><i class="fa fa-instagram"></i></a></li>
                            <li><a target="_blank" href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a></li>
                            <li><a target="_blank" href="https://vimeo.com/"><i class="fa fa-vimeo-square"></i></a></li>
                            <li><a target="_blank" href="https://www.behance.net/"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                    <!-- End Social -->
                </div>
                <!--Footer Info -->
                <div class="row footer-info mb-60">
                    <div class="col-md-3 col-sm-12 col-xs-12 mb-sm-30">
                        <p class="mb-xs-0">Our ante tincidunt tempus, Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros.</p>
                        <a class="btn-link-a" href="about-1.html">Read More</a>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 mb-sm-30 mb-xs-0">
                        <ul class="link">
                            <li><a href="blog-grid-3col.html">Sign in</a></li>

                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 mb-sm-30">
                        <ul class="link">
                            <li><a href="contact-1.html">Contact Us</a></li>

                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <p> 1 Place du Général de Gaulle, 59000 Lille,France.</p>
                        <ul class="link-small">
                            <li><a href="mailto:yourname@domain.com"><i class="fa fa-envelope-o left"></i>hello@mindspirits.com</a></li>
                            <li><a><i class="fa fa-phone left"></i>+33 (0) 012 345 6789</a></li>
                        </ul>
                    </div>
                </div>
                <!-- End Footer Info -->
            </div>

            <hr />

            <!-- Copyright Bar -->
            <section class="copyright ptb-60">
                <div class="container">
                    <p class="">
                        © 2016 <a href="#"><b>Mind Spirit</b></a>. All Rights Reserved.
                        <br />

                    </p>
                </div>
            </section>
            <!-- End Copyright Bar -->

        </footer>
        <!-- END FOOTER -->

app/views/shared/_header.html.erb
<!-- HEADER -->
<header class="header">
    <div class="container">

        <!-- logo -->
        <div class="logo">
          <%= link_to "Mind Spirit", root_path, style:"font-family:'Alex Brush',cursive;font-size: 20px;" %>
        </div>
        <!--End logo-->

        <!-- Navigation Menu -->
        <nav class='navigation'>
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <ul>
                <li>
                    <a href=""><%= current_user.name %></a>
                    <!-- Nav Dropdown -->
                    <ul class="nav-dropdown">
                        <li>
                          <%= link_to user_path(current_user) do %>
                            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                          <% end %>
                        </li>
                        <li>
                          <%= link_to root_path do %>
                            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
                          <% end %>
                        </li>
                        <li>
                          <%= link_to rails_admin_path do %>
                            <i class="fa fa-cogs"></i>  <%= t ".profile", default: "Admin" %>
                          <% end %>
                        </li>
                        <li>
                          <%= link_to destroy_user_session_path, method: :delete do %>
                            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                          <% end %>
                        </li>
                    </ul>
                    <!-- End Nav Dropdown -->
                </li>
            </ul>
          <% else %>
            <ul>
                <li>
                    <a href=""><%= current_user.name %></a>
                    <!-- Nav Dropdown -->
                    <ul class="nav-dropdown">
                        <li >
                          <%= link_to user_path(current_user) do %>
                            <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                          <% end %>
                        </li>
                        <li>
                          <%= link_to root_path do %>
                            <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
                          <% end %>
                        </li>
                        <li>
                          <%= link_to destroy_user_session_path, method: :delete do %>
                            <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                          <% end %>
                        </li>
                    </ul>
                    <!-- End Nav Dropdown -->
                </li>
            </ul>
          <% end %>
        <% else %>
          <ul>
            <li>
              <%= link_to "LOGIN", new_user_session_path %>
            </li>
            <li>
              <%= link_to "SIGN UP", new_user_registration_path %>
            </li>
          </ul>
        <% end %>
        </nav>
        <!--End Navigation Menu -->
    </div>
</header>
<!-- END HEADER -->

app/views/shared/_home_form.html.erb
<div class="container">
    <div class="row">
        <div class='col-sm-4'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" placeholder="Start time" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <div class='col-sm-4'>
            <div class="form-group">
                <div class='input-group date' id='datetimepicker2'>
                    <input type='text' class="form-control" placeholder="End time" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker1').datetimepicker();
            });
        </script>
        <script type="text/javascript">
            $(function () {
                $('#datetimepicker2').datetimepicker();
            });
        </script>
    </div>
</div>

app/views/shared/_modal-map.html.erb
<div id="map" style="width: 100%; height: 600px;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/shared/_modal_map.html.erb
<div id="map" style="width: 100vh; height: 100vh;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function(){
        markers = handler.addMarkers(<%= raw @markers.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });
    })
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <p style="font-family:'Alex Brush',cursive;font-size: 30px;">Mind Spirit</p>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>
      <!-- Profile picture and dropdown -->
      <% if current_user.admin %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu admin">
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to cocktails_path do %>
                  <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
                <% end %>
              </li>
              <li>
                <%= link_to rails_admin_path do %>
                  <i class="fa fa-cogs"></i>  <%= t ".profile", default: "Admin" %>
                <% end %>
              </li>
              <li>
                <%= link_to sidekiq_web_path do %>
                  <i class="fa fa-line-chart"></i>  <%= t ".profile", default: "Sidekiq" %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu non-admin">
              <li>
                <%= link_to user_path(current_user) do %>
                  <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
                <% end %>
              </li>
              <li>
                <%= link_to cocktails_path do %>
                  <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>

    <% else %>

      <!-- Login text link -->

      <%= link_to "LOGIN", new_user_session_path, class: "btn navbar-wagon-item navbar-wagon-button" %>
      <%= link_to "SIGN UP", new_user_registration_path, class: "btn navbar-wagon-item navbar-wagon-button" %>
    <% end %>
  </div>
</div>